### ISSUE TITLE
autosizer blows up when image doesn't end in img

### ISSUE THREAD

**Issue by kb0thn** [aprsworld/diskImageScripts#1]
got all kinds of errors with file named  stikweb_release_20150924

renamed it  stikweb_release_20150924.img and it appears to be working fine

**Comment by kb0thn** [comment]
got the message it initially gives

Usage:
 losetup loop_device                             give info
 losetup -a | --all                              list all used
 losetup -d | --detach <loopdev> [<loopdev> ...] delete
 losetup -f | --find                             find unused
 losetup -c | --set-capacity <loopdev>           resize
 losetup -j | --associated <file> [-o <num>]     list all associated with <file>
 losetup [ options ] {-f|--find|loopdev} <file>  setup

Options:
 -e | --encryption <type> enable data encryption with specified <name/num>
 -h | --help              this help
 -o | --offset <num>      start at offset <num> into file
      --sizelimit <num>   loop limited to only <num> bytes of the file
 -p | --pass-fd <num>     read passphrase from file descriptor <num>
 -r | --read-only         setup read-only loop device
      --show              print device name (with -f <file>)
 -N | --nohashpass        Do not hash the given password (Debian hashes)
 -k | --keybits <num>     specify number of bits in the hashed key given
                          to the cipher.  Some ciphers support several key
                          sizes and might be more efficient with a smaller
                          key size.  Key sizes < 128 are generally not
                          recommended
 -v | --verbose           verbose mode

Usage: e2fsck [-panyrcdfvtDFV] [-b superblock] [-B blocksize]
                [-I inode_buffer_blocks] [-P process_inode_size]
                [-l|-L bad_blocks_file] [-C fd] [-j external_journal]
                [-E extended-options] device

Emergency help:
 -p                   Automatic repair (no questions)
 -n                   Make no changes to the filesystem
 -y                   Assume "yes" to all questions
 -c                   Check for bad blocks and add them to the badblock list
 -f                   Force checking even if filesystem is marked clean
 -v                   Be verbose
 -b superblock        Use alternative superblock
 -B blocksize         Force blocksize when looking for superblock
 -j external_journal  Set location of the external journal
 -l bad_blocks_file   Add to badblocks list
 -L bad_blocks_file   Set badblocks list
resize2fs 1.41.11 (14-Mar-2010)
Usage: resize2fs [-d debug_flags] [-f] [-F] [-M] [-P] [-p] device [new_size]

(standard_in) 1: syntax error
resize2fs 1.41.11 (14-Mar-2010)
Usage: resize2fs [-d debug_flags] [-f] [-F] [-M] [-P] [-p] device [new_size]

Usage:
 losetup loop_device                             give info
 losetup -a | --all                              list all used
 losetup -d | --detach <loopdev> [<loopdev> ...] delete
 losetup -f | --find                             find unused
 losetup -c | --set-capacity <loopdev>           resize
 losetup -j | --associated <file> [-o <num>]     list all associated with <file>
 losetup [ options ] {-f|--find|loopdev} <file>  setup

Options:
 -e | --encryption <type> enable data encryption with specified <name/num>
 -h | --help              this help
 -o | --offset <num>      start at offset <num> into file
      --sizelimit <num>   loop limited to only <num> bytes of the file
 -p | --pass-fd <num>     read passphrase from file descriptor <num>
 -r | --read-only         setup read-only loop device
      --show              print device name (with -f <file>)
 -N | --nohashpass        Do not hash the given password (Debian hashes)
 -k | --keybits <num>     specify number of bits in the hashed key given
                          to the cipher.  Some ciphers support several key
                          sizes and might be more efficient with a smaller
                          key size.  Key sizes < 128 are generally not
                          recommended
 -v | --verbose           verbose mode

(standard_in) 1: syntax error
(standard_in) 3: syntax error
parted: invalid token: 62914560

**Comment by kb0thn** [comment]
tried it on a different system (debian 7) and same thing happened

**Comment by davarus** [comment]
Updated both resize.sh and strip.sh, so they are more robust.  Try them now.  Documentation is at the top of the scripts, but will be adding a README.md to the git repo tomorrow.
